image: node:10.15.1

pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run build-dev
          artifacts:
            - dist/**
      - step:
          name: Deploy
          deployment: staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                S3_BUCKET: $AWS_S3_BUCKET
                LOCAL_PATH: 'dist'
                ACL: 'public-read'
